### ISSUE TITLE
Separate API route to return authors instead of papers

### ISSUE THREAD

**Issue by boogheta** [medialab/halexp#15]
In addition to the current query route (which could maybe be renamed as papers), we need an alternate querying route that would return authors instead of papers.
This should :
- [x] aggregate all authors of the N best fitting papers of a query and return the nb_hits best
- [x] aggregation should be tried two ways (maybe keep both as optional argument?)
  - [x] either a set of unique authors encountered in the papers results, in the order they're met, or randomly ordered?
  - [x] or a set of ranked best authors encountered in the papers results using some kind of heuristic based on the scoring of their papers and the number of those (and maybe also the total number of papers of the author on HAL, but that might not be easy to have that value on runtime)
- [x] have an optional argument to define the number of first paper results to consider to do the agregation (default value to determine for something reactive enough but let's try something between 1000 and 10000 maybe?)
- [ ] have an optional argument to define whether coauthors should be considered into the agregation or not
- [x] have an optional integer argument to define the max number of best fitting papers to return along with each author (default value to determine but we can start with something between 3 and 5 I guess)

**Warning:** all authors do not necessarily have an idHal, so maybe we should rather work with digital ids instead (but returning also idHal should be useful for generating links to authors pages)

**Comment by jimenaRL** [comment]
I did took everything in except the coauthors since the ISI ask for use all of them.
