### ISSUE TITLE
Experiment with full text of Open Access articles

### ISSUE THREAD

**Issue by boogheta** [medialab/halexp#2]

**Comment by jimenaRL** [comment]
Open Access is a repository where we can find the whole body of HAL articles ?
Do you have a link @boogheta  ?

**Comment by boogheta** [comment]
You could add to the fields requested to the API `openAccess_bool` which will let you know whether a publication is or not openaccess, and is so there seems to be a `fulltext_t` field that is supposed to be an indexed text version of the pdf, to try

The full documentation on the HAL API fields is there: https://api.archives-ouvertes.fr/docs/search/?schema=fields#fields
