### ISSUE TITLE
Setup the HAL query as environment variable

### ISSUE THREAD

**Issue by boogheta** [medialab/halexp#8]

**Comment by jimenaRL** [comment]
Je ne comprends très bien compris ce besoin.
On avaot d'abord parlé d'avoir une config yaml pour configurer la query, chose faite ici  https://github.com/medialab/halexp/blob/main/config.yaml

**Comment by boogheta** [comment]
Cela nous permettrait de réutiliser le code pour d'autres usages, par exemple pour le médialab. En l'état la configuration est générale et dans le repo. Avec des variables d'environnement on pourrait configurer plusieurs déploiements automatiques pour différentes bases.
Mais le besoin est de plus long terme, dans le seul cadre du travail pour l'ICI, cela fonctionne bien comme cela.
